function Merge-RVToolsExcelFiles {
    <#
    .SYNOPSIS
        Merges multiple RVTools Excel files into a single consolidated file.

    .DESCRIPTION
        This function takes multiple Excel files generated by RVTools chunked export
        and merges them into a single file, handling duplicate vMetaData tabs properly.

    .PARAMETER SourceFiles
        Array of source Excel file paths to merge.

    .PARAMETER DestinationFile
        Path for the merged output file.

    .EXAMPLE
        Merge-RVToolsExcelFiles -SourceFiles @("file1.xlsx", "file2.xlsx") -DestinationFile "merged.xlsx"

    .OUTPUTS
        System.Boolean - Returns $true if merge was successful, $false otherwise.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string[]]$SourceFiles,
        
        [Parameter(Mandatory)]
        [string]$DestinationFile
    )
    
    # Filter to only existing files
    $existingFiles = $SourceFiles | Where-Object { Test-Path $_ }
    
    if ($existingFiles.Count -eq 0) {
        Write-RVToolsLog -Message "No source files exist to merge" -Level 'ERROR'
        return $false
    }
    
    Write-RVToolsLog -Message "Merging $($existingFiles.Count) Excel files into $DestinationFile"
    
    try {
        # Load the Excel COM object
        $excel = New-Object -ComObject Excel.Application
        $excel.Visible = $false
        $excel.DisplayAlerts = $false
        
        # Open the first file as the destination workbook
        $destinationWorkbook = $excel.Workbooks.Open($existingFiles[0])
        Write-RVToolsLog -Message "Opened first file as base: $($existingFiles[0])" -Level 'DEBUG'
        
        # Process remaining files (if any)
        for ($i = 1; $i -lt $existingFiles.Count; $i++) {
            $sourceFile = $existingFiles[$i]
            Write-RVToolsLog -Message "Processing $sourceFile" -Level 'DEBUG'
            $sourceWorkbook = $excel.Workbooks.Open($sourceFile)
            
            # Copy worksheets from source to destination, but skip vMetaData tabs from subsequent files
            foreach ($worksheet in $sourceWorkbook.Worksheets) {
                # Skip vMetaData tabs from files after the first one (they should be identical)
                if ($worksheet.Name -eq 'vMetaData') {
                    Write-RVToolsLog -Message "Skipping duplicate vMetaData tab from $sourceFile" -Level 'DEBUG'
                    continue
                }
                $worksheet.Copy([System.Reflection.Missing]::Value, $destinationWorkbook.Worksheets.Item($destinationWorkbook.Worksheets.Count))
            }
            
            $sourceWorkbook.Close($false)
            Write-RVToolsLog -Message "Merged worksheets from $sourceFile (excluding duplicate vMetaData)" -Level 'DEBUG'
        }
        
        # Save the merged workbook with new name
        $destinationWorkbook.SaveAs($DestinationFile)
        $destinationWorkbook.Close($false)
        $excel.Quit()
        
        # Clean up COM objects
        [System.Runtime.Interopservices.Marshal]::ReleaseComObject($destinationWorkbook) | Out-Null
        [System.Runtime.Interopservices.Marshal]::ReleaseComObject($excel) | Out-Null
        [System.GC]::Collect()
        
        Write-RVToolsLog -Message "Successfully merged $($existingFiles.Count) Excel files into $DestinationFile" -Level 'SUCCESS'
        return $true
    } catch {
        Write-RVToolsLog -Message "Failed to merge Excel files: $($_.Exception.Message)" -Level 'ERROR'
        
        # Cleanup on error
        try {
            if ($destinationWorkbook) { $destinationWorkbook.Close($false) }
            if ($excel) { $excel.Quit() }
        } catch { }
        
        return $false
    }
}
